# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0002_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='location',
            name='category',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
