# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0008_remove_profile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phoneNumber',
            field=models.CharField(max_length=10),
        ),
    ]
