# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0010_auto_20171031_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='familyName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='firstName',
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
