# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0011_auto_20171031_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='rating',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
